services:
    tests-ui:
      init: true
      image: ghcr.io/wisetrout/playwright-ui:latest
      ports:
        - ${TESTS_MENU_PORT:-8000}:3000
        - ${TESTS_RESULTS_PORT:-8323}:9323
      environment:
        - TESTS_MENU_PORT
        - TESTS_RESULTS_PORT
      security_opt:
        - seccomp=seccomp_profile.json
      volumes:
        - type: bind
          source: ./hooks
          target: /app/hooks
        - type: volume
          target: /app/settings